[package]
name = "tibia-autohealer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
enigo = "0.1.3"
regex = "1.10.3"
xcap = "0.0.3"
